// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srmoewhongrgbhhlknvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybW9ld2hvbmdyZ2JoaGxrbnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzIxNDcsImV4cCI6MjA3Mzg0ODE0N30.ePqAQE8SZ_IpEHg4BpJkrxY827kRhPl3uiaah-R9Iuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});